### ISSUE TITLE
reducing the Wikidata output files

### ISSUE THREAD

**Issue by tabbassidaloii** [sec2pri/mapping_preprocessing#13]
@DeniseSl22 , I suggest removing the prefix before the IDs to reduce the file size, e.g. [here](https://github.com/sec2pri/mapping_preprocessing/blob/aec22108b11f9f93e94cf14ffabfecb450ffde53/datasources/Wikidata/data/chemicalRedirectsWikidata.csv), instead of `http://www.wikidata.org/entity/Q209355,http://www.wikidata.org/entity/Q72471241`, use `Q209355,Q72471241`.

**Comment by DeniseSl22** [comment]
Yes, I can do that in the query, but it might affect the time to run the query itself; so I need to check if we don't get a time out then

**Comment by tabbassidaloii** [comment]
Maybe, adding a bash script for excluding them after downloading and before saving would be better. I can do that.
