### ISSUE TITLE
If timeout wikidata, push github action to github issue

### ISSUE THREAD

**Issue by DeniseSl22** [sec2pri/mapping_preprocessing#28]
```
          ##Check new data, fail job if query timeout has occured
          cd datasources/Wikidata/results
          for File in *.tsv ##Only for tsv files
          do
            if grep -q TimeoutException "$File"; then
              echo "Query Timeout occurred for file: " "$File" 
              echo "Wikidata data will not be updated"
              head -n 20 "$File" 
              exit 1
            else
              echo "No Query Timeout detected for file: " "$File" 
            fi
          done
```

**Comment by jmillanacosta** [comment]
This can be solved as with the ChEBI workflow

Use this variable:
https://github.com/sec2pri/mapping_preprocessing/blob/cbe925c77fc56eea2c36cb8ce4c02edb9cba2057/.github/workflows/chebi.yml#L37

And write this:

https://github.com/sec2pri/mapping_preprocessing/blob/cbe925c77fc56eea2c36cb8ce4c02edb9cba2057/.github/workflows/chebi.yml#L50

At the top of the post-issue step:

https://github.com/sec2pri/mapping_preprocessing/blob/cbe925c77fc56eea2c36cb8ce4c02edb9cba2057/.github/workflows/chebi.yml#L96-L115
