### ISSUE TITLE
GA for NCBI

### ISSUE THREAD

**Issue by tabbassidaloii** [sec2pri/mapping_preprocessing#44]
This database pushes daily changes so there is no need to check the version:
`Important consideration, this job should be run once a month.`
- [ ] download these files:
    - [ ]  https://ftp.ncbi.nih.gov/gene/DATA/gene_history.gz 
    - [ ] https://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz
- [ ] run the R script

`

    name: Run R Script with Arguments

    on:
      push:
        branches:
          - main  

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up R
          uses: r-lib/actions/setup-r@v1

        - name: Install dependencies
          run: |
            Rscript -e ' install.packages("dplyr")'

        - name: Run R script with arguments
          run: Rscript ncbi.R $arg1 $arg2 $arg3
          env:
            arg1: "2024-01-26" # the date that the files were dowanloaded
            arg2: "gene_history" # the file downloaded from https://ftp.ncbi.nih.gov/gene/DATA/gene_history.gz
            arg3: "gene_info"  # the file downloaded from https://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz
            
            # three output files are:
            # NCBI_alias&prev2symbol.tsv,NCBI_priIDs.tsv,NCBI_secID2priID.tsv

`

- [ ] Download the file from zenodo as explained [here](https://github.com/sec2pri/mapping_preprocessing/blob/main/.github/workflows/zenodo_test.yml)
     - [ ] replace the file_name on [line #19](https://github.com/sec2pri/mapping_preprocessing/blob/f2f7ce4fa9515540bdffad0e3b9815dbdfb08269/.github/workflows/zenodo_test.yml#L19C1-L20C1) with to_check_from_zenodo value from https://github.com/sec2pri/mapping_preprocessing/blob/main/datasources/ncbi/config
- [ ] compare its `secondaryID` column with the `secondaryID` column of the same output of rscript file (NCBI_secID2priID.tsv)
- [ ] add the comparison results to the posted issue

**Comment by jmillanacosta** [comment]
What's the status on this? Closes with #62 ?

**Comment by tabbassidaloii** [comment]
Working on it, the last step (comparing the old and new needs some modification)
