### ISSUE TITLE
chebi GA

### ISSUE THREAD

**Issue by tabbassidaloii** [sec2pri/mapping_preprocessing#47]
- [ ] Download the file from zenodo as explained [here](https://github.com/sec2pri/mapping_preprocessing/blob/main/.github/workflows/zenodo_test.yml)
    - [ ] replace the file_name on [line #19](https://github.com/sec2pri/mapping_preprocessing/blob/f2f7ce4fa9515540bdffad0e3b9815dbdfb08269/.github/workflows/zenodo_test.yml#L19C1-L20C1) with to_check_from_zenodo value from https://github.com/sec2pri/mapping_preprocessing/blob/main/datasources/chebi/chebi.config
- [ ] compare its `secondaryID` column with the `secondaryID` column of the same output of .jar file (ChEBI_secID2priID.tsv)
- [ ] add the comparison results to the posted issue

**Comment by jmillanacosta** [comment]
Related issue: #43
